/**
 * ADDITIVE demo overlay for the `vayu` schema — pitch-ready transactional data.
 *
 * ARCHITECTURE.md §10 / §4.1. Companion to `seed_vayu.mjs`, but where that
 * script wipes-and-reseeds a small hand-authored mockup dataset, this one must
 * NEVER wipe anything: the `vayu` schema already holds the real reference
 * dataset (55 drugs, 49 institutions, 88,224 stock-ledger rows, 8,894 purchase
 * orders, thousands of batches) generated by the medtrack data-gen pipeline.
 * That dataset is what makes the analytics screens (forecast, vendor
 * scorecard, stock health, expiry) look real, and it must survive every run of
 * this script untouched.
 *
 * What's missing for the demo is TRANSACTIONAL flow data: the reference
 * dataset carries almost no SupplyOrder / Shipment rows, so the Approvals
 * queue, Dispatch board, Telemetry console and dashboard cards render empty.
 * This script layers ~14 supply orders, ~9 in-flight shipments (one hero
 * cold-chain excursion story), dense telemetry, and a handful of complaints
 * ON TOP of the existing data — it only reads drugs/institutions/batches to
 * discover real ids at runtime, never invents or deletes them.
 *
 * Idempotent re-run: every row this script creates is keyed off a fixed set of
 * UUID constants (DEMO_IDS below). On startup it deletes ONLY those ids and
 * their children (child-first), then recreates them — so running it twice
 * leaves the same row count rather than duplicating, without ever touching
 * `drug`, `institution`, `batch`, `stockLedger`, `purchaseOrder`, `vendor`,
 * `currentStock`, `diseaseSignal`, or `consumptionFeed`.
 *
 *   node backend/data-gen/seed_demo_overlay.mjs
 *   node backend/data-gen/seed_demo_overlay.mjs --keep   (skip if demo rows already present)
 */

import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { PrismaClient } = require('../vayu-api/node_modules/.prisma/client');

const prisma = new PrismaClient();
const KEEP = process.argv.includes('--keep');

const DAY = 86_400_000;
const HOUR = 3_600_000;
const MIN = 60_000;
const now = Date.now();
/** Minutes-ago helper — the demo orders/shipments are framed as "just now". */
const ago = (mins) => new Date(now - mins * MIN);

// ─── Fixed ids (namespace for this script's own rows) ───────────────────────
// Hardcoded UUIDs so the overlay is idempotent: on every run we delete exactly
// these rows (and their children) before recreating them, and never touch any
// row this script didn't create. Grouped by kind for readability.
const DEMO_IDS = {
  orders: {
    // Distinct leading segments: the UI truncates ids to 8 chars for display,
    // so a shared prefix would render every row as the same reference.
    pending: [
      '5a01c7d2-0000-4000-8000-000000000001',
      '5b12e8f3-0000-4000-8000-000000000002',
      '5c23f904-0000-4000-8000-000000000003',
      '5d34a015-0000-4000-8000-000000000004',
      '5e45b126-0000-4000-8000-000000000005',
    ],
    approved: [
      '6a56c237-0000-4000-8000-000000000001',
      '6b67d348-0000-4000-8000-000000000002',
      '6c78e459-0000-4000-8000-000000000003',
      '6d89f56a-0000-4000-8000-000000000004',
      '6e9a067b-0000-4000-8000-000000000005',
    ],
    partial: [
      '7aab178c-0000-4000-8000-000000000001',
      '7bbc289d-0000-4000-8000-000000000002',
    ],
    rejected: ['8ccd39ae-0000-4000-8000-000000000001'],
  },
  shipments: [
    '9de4a1bf-0000-4000-8000-000000000001', // hero cold-chain excursion story
    '9ef5b2c0-0000-4000-8000-000000000002',
    'a0a6c3d1-0000-4000-8000-000000000003',
    'a1b7d4e2-0000-4000-8000-000000000004',
    'a2c8e5f3-0000-4000-8000-000000000005',
    'a3d9f604-0000-4000-8000-000000000006',
    'a4ea0715-0000-4000-8000-000000000007',
    'a5fb1826-0000-4000-8000-000000000008',
    'a60c2937-0000-4000-8000-000000000009',
  ],
};

/**
 * Ids from an earlier revision of this script, whose first 8 chars collided
 * (every order rendered as "a1111111"). Purged alongside the current ids so
 * a re-run leaves no orphans behind.
 */
const LEGACY_ORDER_IDS = [
  'a1111111-0000-4000-8000-000000000001',
  'a1111111-0000-4000-8000-000000000002',
  'a1111111-0000-4000-8000-000000000003',
  'a1111111-0000-4000-8000-000000000004',
  'a1111111-0000-4000-8000-000000000005',
  'a2222222-0000-4000-8000-000000000001',
  'a2222222-0000-4000-8000-000000000002',
  'a2222222-0000-4000-8000-000000000003',
  'a2222222-0000-4000-8000-000000000004',
  'a2222222-0000-4000-8000-000000000005',
  'a3333333-0000-4000-8000-000000000001',
  'a3333333-0000-4000-8000-000000000002',
  'a4444444-0000-4000-8000-000000000001',
];
const LEGACY_SHIPMENT_IDS = [
  'b1111111-0000-4000-8000-000000000001',
  'b1111111-0000-4000-8000-000000000002',
  'b1111111-0000-4000-8000-000000000003',
  'b1111111-0000-4000-8000-000000000004',
  'b1111111-0000-4000-8000-000000000005',
  'b1111111-0000-4000-8000-000000000006',
  'b1111111-0000-4000-8000-000000000007',
  'b1111111-0000-4000-8000-000000000008',
  'b1111111-0000-4000-8000-000000000009',
];

const ALL_ORDER_IDS = [
  ...DEMO_IDS.orders.pending,
  ...DEMO_IDS.orders.approved,
  ...DEMO_IDS.orders.partial,
  ...DEMO_IDS.orders.rejected,
  ...LEGACY_ORDER_IDS,
];
const ALL_SHIPMENT_IDS = [...DEMO_IDS.shipments, ...LEGACY_SHIPMENT_IDS];
const HERO_SHIPMENT_ID = DEMO_IDS.shipments[0];

/** Cleans up ONLY rows tagged with our fixed ids, child-first. Never touches
 *  reference tables (drug/institution/batch/stockLedger/purchaseOrder/vendor/
 *  currentStock/diseaseSignal/consumptionFeed). */
/** Marker prefix on complaint descriptions so this script's own complaint
 *  rows (which have no fixed id — Complaint.id has no default we control
 *  cheaply while staying idempotent) can be found and removed on a re-run
 *  without touching any complaint the base dataset or another process created. */
const COMPLAINT_MARKER = '[demo-overlay]';

async function cleanupPreviousRun() {
  await prisma.excursion.deleteMany({ where: { shipmentId: { in: ALL_SHIPMENT_IDS } } });
  await prisma.telemetryPoint.deleteMany({ where: { shipmentId: { in: ALL_SHIPMENT_IDS } } });
  await prisma.complaint.deleteMany({
    where: {
      OR: [
        { shipmentId: { in: ALL_SHIPMENT_IDS } },
        { description: { startsWith: COMPLAINT_MARKER } },
      ],
    },
  });
  await prisma.shipmentBatch.deleteMany({ where: { shipmentId: { in: ALL_SHIPMENT_IDS } } });
  await prisma.shipment.deleteMany({ where: { id: { in: ALL_SHIPMENT_IDS } } });
  await prisma.supplyOrderLine.deleteMany({ where: { orderId: { in: ALL_ORDER_IDS } } });
  await prisma.supplyOrder.deleteMany({ where: { id: { in: ALL_ORDER_IDS } } });
}

/** Discover real ids at runtime — never hardcode drug/institution ids. */
async function discoverReferenceData() {
  const coldDrugs = await prisma.drug.findMany({ where: { coldChain: true }, take: 10 });
  const ambientDrugs = await prisma.drug.findMany({ where: { coldChain: false }, take: 20 });
  const facilities = await prisma.institution.findMany({
    where: { type: { in: ['DISTRICT_HOSPITAL', 'CHC', 'PHC'] } },
    take: 20,
  });
  const warehouses = await prisma.institution.findMany({ where: { type: 'WAREHOUSE' }, take: 5 });
  const batches = await prisma.batch.findMany({ take: 200 });

  if (coldDrugs.length === 0) {
    console.error(
      'No cold-chain drugs found — seed the base medtrack dataset first (backend/data-gen).',
    );
    process.exit(1);
  }
  if (ambientDrugs.length === 0) {
    console.error('No ambient (non-cold-chain) drugs found — seed the base dataset first.');
    process.exit(1);
  }
  if (facilities.length === 0) {
    console.error(
      'No DISTRICT_HOSPITAL/CHC/PHC institutions found — seed the base dataset first.',
    );
    process.exit(1);
  }
  if (batches.length === 0) {
    console.error('No batches found — seed the base dataset first.');
    process.exit(1);
  }

  const warehouse = warehouses[0] ?? facilities[0];

  return { coldDrugs, ambientDrugs, facilities, warehouse, batches };
}

/** Pick a stable-but-varied subset without repeating the same facility twice
 *  in a row, so the queue reads like a real network rather than one site. */
function pick(list, i) {
  return list[i % list.length];
}

function batchesFor(batches, drugId, count = 1) {
  const matches = batches.filter((b) => b.drugId === drugId);
  const pool = matches.length > 0 ? matches : batches;
  return pool.slice(0, count);
}

async function createOrders({ facilities, coldDrugs, ambientDrugs }) {
  const drugsFor = (i) => {
    const cold = pick(coldDrugs, i);
    const ambient1 = pick(ambientDrugs, i);
    const ambient2 = pick(ambientDrugs, i + 3);
    return [ambient1, ambient2, cold];
  };

  const mkOrder = async (id, institution, status, minsAgo, lineSpecs, window, reason) =>
    prisma.supplyOrder.create({
      data: {
        id,
        institutionId: institution.id,
        status,
        requestedWindow: window ?? null,
        rejectionReason: reason ?? null,
        placedAt: ago(minsAgo),
        lines: {
          create: lineSpecs.map(([drug, req, appr]) => ({
            drugId: drug.id,
            qtyRequested: req,
            qtyApproved: appr ?? null,
          })),
        },
      },
      include: { lines: true },
    });

  const orders = [];

  // 5 PENDING, ages spread 20 minutes to 9 hours so aging badges have range.
  const pendingAges = [20, 95, 210, 340, 545]; // minutes: 20m, 1.6h, 3.5h, 5.7h, 9.1h
  const pendingQty = [
    [900, 400],
    [3000, 1200],
    [12000, 6000],
    [220, 60],
    [1800, 700],
  ];
  for (let i = 0; i < DEMO_IDS.orders.pending.length; i++) {
    const inst = pick(facilities, i);
    const [d1, d2, d3] = drugsFor(i);
    const [q1, q2] = pendingQty[i];
    orders.push(
      await mkOrder(
        DEMO_IDS.orders.pending[i],
        inst,
        'PENDING',
        pendingAges[i],
        i % 2 === 0
          ? [[d1, q1], [d2, q2]]
          : [[d1, q1], [d2, q2], [d3, Math.max(60, Math.round(q2 / 4))]],
        '19–21 Aug',
      ),
    );
  }

  // 5 APPROVED, fully approved at requested qty.
  const approvedQty = [
    [1500, 500, 150],
    [8000, 3000],
    [400, 180],
    [15000, 4200, 900],
    [2600, 1100],
  ];
  const approvedAges = [180, 260, 420, 480, 600];
  for (let i = 0; i < DEMO_IDS.orders.approved.length; i++) {
    const inst = pick(facilities, i + 2);
    const [d1, d2, d3] = drugsFor(i + 1);
    const qty = approvedQty[i];
    const lines =
      qty.length === 3
        ? [[d1, qty[0], qty[0]], [d2, qty[1], qty[1]], [d3, qty[2], qty[2]]]
        : [[d1, qty[0], qty[0]], [d2, qty[1], qty[1]]];
    orders.push(
      await mkOrder(
        DEMO_IDS.orders.approved[i],
        inst,
        'APPROVED',
        approvedAges[i],
        lines,
        '18–19 Aug',
      ),
    );
  }

  // 2 PARTIAL — qtyApproved < qtyRequested on at least one line.
  orders.push(
    await mkOrder(
      DEMO_IDS.orders.partial[0],
      pick(facilities, 6),
      'PARTIAL',
      300,
      [
        [pick(ambientDrugs, 6), 5000, 2200],
        [pick(coldDrugs, 2), 600, 600],
      ],
      '17–18 Aug',
    ),
  );
  orders.push(
    await mkOrder(
      DEMO_IDS.orders.partial[1],
      pick(facilities, 9),
      'PARTIAL',
      360,
      [
        [pick(ambientDrugs, 9), 900, 300],
        [pick(ambientDrugs, 12), 2400, 2400],
        [pick(coldDrugs, 3), 300, 100],
      ],
      '17–18 Aug',
    ),
  );

  // 1 REJECTED with a rejectionReason.
  orders.push(
    await mkOrder(
      DEMO_IDS.orders.rejected[0],
      pick(facilities, 11),
      'REJECTED',
      540,
      [[pick(coldDrugs, 4), 500]],
      '16–17 Aug',
      'Cold-chain capacity unavailable for this corridor in the requested window',
    ),
  );

  return orders;
}

/** Plausible Maharashtra coordinates for live-map markers. */
const MH_LAT = [18.4, 20.2];
const MH_LNG = [72.7, 75.9];
function lerp(a, b, t) {
  return a + (b - a) * t;
}
function routePoint(seed, t) {
  // Deterministic pseudo-route per shipment: a straight-ish line between two
  // seeded endpoints inside the Maharashtra bounding box, nudged by seed.
  const latA = MH_LAT[0] + ((seed * 37) % 100) / 100 * (MH_LAT[1] - MH_LAT[0]);
  const latB = MH_LAT[0] + ((seed * 53 + 17) % 100) / 100 * (MH_LAT[1] - MH_LAT[0]);
  const lngA = MH_LNG[0] + ((seed * 61 + 5) % 100) / 100 * (MH_LNG[1] - MH_LNG[0]);
  const lngB = MH_LNG[0] + ((seed * 29 + 41) % 100) / 100 * (MH_LNG[1] - MH_LNG[0]);
  return { lat: Number(lerp(latA, latB, t).toFixed(5)), lng: Number(lerp(lngA, lngB, t).toFixed(5)) };
}

async function createShipments({ orders, warehouse, batches }) {
  const approvedOrders = orders.filter((o) => o.status === 'APPROVED' || o.status === 'PARTIAL');
  const shipments = [];

  const mkShipment = async (id, order, status, opts) => {
    const s = await prisma.shipment.create({
      data: {
        id,
        supplyOrderId: order.id,
        originWarehouseId: warehouse.id,
        destinationInstitution: order.institutionId,
        status,
        coldChain: opts.cold ?? false,
        dispatchedAt: opts.dispatchedAt ?? null,
        etaAt: opts.etaAt ?? null,
        deliveredAt: opts.deliveredAt ?? null,
        progressPct: opts.progress ?? null,
        lastKnownLat: opts.pos?.lat ?? null,
        lastKnownLng: opts.pos?.lng ?? null,
        lastTempC: opts.temp ?? null,
        excursionCount: 0,
      },
    });
    // Link 1-2 batches matching the order's lines so the trace screen has data.
    const lineDrugIds = order.lines.map((l) => l.drugId);
    let qtySeed = 0;
    for (const drugId of lineDrugIds.slice(0, 2)) {
      const [b] = batchesFor(batches, drugId, 1);
      if (b) {
        qtySeed += 1;
        await prisma.shipmentBatch.create({
          data: { shipmentId: s.id, batchId: b.id, quantity: Math.min(b.quantity, 100 * qtySeed) },
        });
      }
    }
    return s;
  };

  // progressPct spread across the range, varied status, roughly half cold-chain.
  // Index 0 is the hero shipment (DEMO_IDS.shipments[0] / HERO_SHIPMENT_ID):
  // ~72% progress, recovering from its excursion peak (~12.4C -> lastTempC
  // just above band as it settles back down), MAJOR severity — the demo's
  // headline cold-chain story.
  const specs = [
    // [status, cold, progress, tempC, dispatchedHoursAgo, etaHoursFromNow]
    { status: 'IN_TRANSIT', cold: true, progress: 0.72, temp: 8.7, dispHrsAgo: 4.0, etaHrsAway: 1.6 }, // hero
    { status: 'IN_TRANSIT', cold: true, progress: 0.18, temp: 4.4, dispHrsAgo: 1.0, etaHrsAway: 4.5 },
    { status: 'IN_TRANSIT', cold: false, progress: 0.41, temp: null, dispHrsAgo: 2.5, etaHrsAway: 3.6 },
    { status: 'IN_TRANSIT', cold: true, progress: 0.58, temp: 5.1, dispHrsAgo: 3.2, etaHrsAway: 2.3 },
    { status: 'IN_TRANSIT', cold: true, progress: 0.84, temp: 7.6, dispHrsAgo: 5.5, etaHrsAway: 0.9 },
    { status: 'OUT_FOR_DELIVERY', cold: false, progress: 0.94, temp: null, dispHrsAgo: 6.2, etaHrsAway: 0.2 },
    { status: 'DELIVERED', cold: true, progress: 1, temp: 5.8, dispHrsAgo: 9, etaHrsAway: -1, delivered: true },
    { status: 'DELIVERED', cold: false, progress: 1, temp: null, dispHrsAgo: 12, etaHrsAway: -2, delivered: true },
    { status: 'EXCEPTION', cold: true, progress: 0.63, temp: 15.2, dispHrsAgo: 4.5, etaHrsAway: 1.5 },
  ];

  for (let i = 0; i < DEMO_IDS.shipments.length; i++) {
    const order = pick(approvedOrders, i);
    const spec = specs[i];
    const dispatchedAt = ago(spec.dispHrsAgo * 60);
    const etaAt = new Date(now + spec.etaHrsAway * HOUR);
    const deliveredAt = spec.delivered
      ? new Date(etaAt.getTime() - 15 * MIN) // delivered slightly before ETA -> on-time
      : null;
    const pos = routePoint(i + 1, spec.progress);
    shipments.push(
      await mkShipment(DEMO_IDS.shipments[i], order, spec.status, {
        cold: spec.cold,
        progress: spec.progress,
        temp: spec.temp,
        dispatchedAt,
        etaAt,
        deliveredAt,
        pos,
      }),
    );
  }

  return shipments;
}

/** Hero shipment: dense telemetry with a visible excursion breach, everyone
 *  else gets a lighter believable walk inside 2-8C (or none if ambient). */
async function createTelemetryAndExcursions({ shipments }) {
  const POINTS = 200;
  let excursionRows = 0;

  for (let idx = 0; idx < shipments.length; idx++) {
    const s = shipments[idx];
    if (!s.coldChain) continue;

    const isHero = s.id === HERO_SHIPMENT_ID;
    const tripStartMs = now - 6 * HOUR; // wide enough window to place 200 points
    const tripEndMs = now;
    const stepMs = (tripEndMs - tripStartMs) / (POINTS - 1);

    const pts = [];
    // Excursion window: roughly the middle third of the hero trip, ~41 minutes.
    const excursionStartFrac = 0.42;
    const excursionEndFrac = 0.42 + 41 / ((tripEndMs - tripStartMs) / MIN);

    for (let i = 0; i < POINTS; i++) {
      const t = new Date(tripStartMs + i * stepMs);
      const frac = i / (POINTS - 1);
      const { lat, lng } = routePoint(idx + 1, frac);

      let temp;
      if (isHero && frac >= excursionStartFrac && frac <= excursionEndFrac) {
        // Breach: ramps above 8C, peaks ~12.4C, back down — visible red spike.
        const local = (frac - excursionStartFrac) / (excursionEndFrac - excursionStartFrac);
        const bump = Math.sin(local * Math.PI); // 0 -> 1 -> 0
        temp = 6.5 + bump * 5.9; // peak ~12.4
      } else {
        // Believable in-band walk, 2-8C.
        temp = 4.6 + Math.sin(i / 7) * 1.3 + Math.sin(i / 23) * 0.6;
        temp = Math.min(7.8, Math.max(2.2, temp));
      }

      pts.push({
        shipmentId: s.id,
        ts: t,
        lat,
        lng,
        tempC: Number(temp.toFixed(2)),
        humidity: Number((55 + Math.sin(i / 11) * 8).toFixed(1)),
        source: 'SIMULATED',
        deviceId: `sim-${idx + 1}`,
      });
    }
    await prisma.telemetryPoint.createMany({ data: pts });

    if (isHero) {
      const startedAt = new Date(tripStartMs + excursionStartFrac * (tripEndMs - tripStartMs));
      const endedAt = new Date(tripStartMs + excursionEndFrac * (tripEndMs - tripStartMs));
      await prisma.excursion.create({
        data: {
          shipmentId: s.id,
          startedAt,
          endedAt,
          minTempC: 8.1,
          maxTempC: 12.4,
          durationMin: 41,
          severity: 'MAJOR',
          acknowledged: false,
        },
      });
      await prisma.shipment.update({ where: { id: s.id }, data: { excursionCount: 1 } });
      excursionRows += 1;
    } else if (s.status === 'EXCEPTION') {
      // The other EXCEPTION shipment also gets a matching excursion so its
      // status is explained by real telemetry, not just a label.
      const startedAt = ago(Math.max(30, (6 * 60) * 0.55));
      await prisma.excursion.create({
        data: {
          shipmentId: s.id,
          startedAt,
          endedAt: null,
          minTempC: 8.4,
          maxTempC: 15.2,
          durationMin: 96,
          severity: 'CRITICAL',
          acknowledged: false,
        },
      });
      await prisma.shipment.update({ where: { id: s.id }, data: { excursionCount: 1 } });
      excursionRows += 1;
    }
  }

  return excursionRows;
}

async function createComplaints({ shipments, facilities, coldDrugs, ambientDrugs, batches }) {
  const hero = shipments.find((s) => s.id === HERO_SHIPMENT_ID);
  const exception = shipments.find((s) => s.status === 'EXCEPTION' && s.id !== HERO_SHIPMENT_ID);
  const delivered = shipments.filter((s) => s.status === 'DELIVERED');

  const complaintSpecs = [
    {
      shipment: hero,
      drug: pick(coldDrugs, 0),
      institution: pick(facilities, 0),
      category: 'TEMP_DAMAGE',
      description: 'Vials warm to the touch on arrival; excursion logged in transit matches complaint window.',
      status: 'INVESTIGATING',
      assignedTeam: 'LOGISTICS',
      photos: 2,
      filedMinsAgo: 45,
    },
    {
      shipment: exception,
      drug: pick(coldDrugs, 1),
      institution: pick(facilities, 3),
      category: 'TEMP_DAMAGE',
      description: 'Carton warm at dock, driver reports AC unit fault mid-route.',
      status: 'OPEN',
      assignedTeam: null,
      photos: 1,
      filedMinsAgo: 90,
    },
    {
      shipment: delivered[0] ?? null,
      drug: pick(ambientDrugs, 2),
      institution: pick(facilities, 5),
      category: 'QTY_MISMATCH',
      description: 'Delivered carton short by two cases against the manifest.',
      status: 'INVESTIGATING',
      assignedTeam: 'LOGISTICS',
      photos: 0,
      filedMinsAgo: 180,
    },
    {
      shipment: delivered[1] ?? null,
      drug: pick(ambientDrugs, 5),
      institution: pick(facilities, 7),
      category: 'SEAL_TAMPERED',
      description: 'Outer seal broken on two cartons; contents replaced from backup stock.',
      status: 'RESOLVED',
      assignedTeam: 'QC',
      photos: 3,
      filedMinsAgo: 400,
    },
    {
      shipment: null,
      drug: pick(coldDrugs, 2),
      institution: pick(facilities, 9),
      category: 'NEAR_EXPIRY',
      description: 'Vaccine delivered with under four months of shelf life remaining.',
      status: 'OPEN',
      assignedTeam: 'QC',
      photos: 0,
      filedMinsAgo: 260,
    },
  ];

  let created = 0;
  for (const spec of complaintSpecs) {
    const [b] = batchesFor(batches, spec.drug.id, 1);
    await prisma.complaint.create({
      data: {
        shipmentId: spec.shipment?.id ?? null,
        batchId: b?.id ?? null,
        drugId: spec.drug.id,
        institutionId: spec.institution.id,
        category: spec.category,
        description: `${COMPLAINT_MARKER} ${spec.description}`,
        photoUrls: Array.from({ length: spec.photos }, (_, i) => `https://example.invalid/evidence/${spec.category}-${i + 1}.jpg`),
        filedAt: ago(spec.filedMinsAgo),
        status: spec.status,
        assignedTeam: spec.assignedTeam,
      },
    });
    created += 1;
  }
  return created;
}

async function main() {
  if (KEEP) {
    const existing = await prisma.supplyOrder.count({ where: { id: { in: ALL_ORDER_IDS } } });
    if (existing > 0) {
      console.log('demo overlay already present — nothing to do (--keep)');
      return;
    }
  }

  console.log('discovering reference data (drugs, institutions, batches)...');
  const ref = await discoverReferenceData();
  console.log(
    `  found ${ref.coldDrugs.length} cold-chain drugs, ${ref.ambientDrugs.length} ambient drugs, ` +
      `${ref.facilities.length} facilities, warehouse=${ref.warehouse.name}, ${ref.batches.length} batches sampled`,
  );

  console.log('cleaning up any previous run of this overlay (by fixed id, not reference data)...');
  await cleanupPreviousRun();

  console.log('creating supply orders...');
  const orders = await createOrders(ref);
  console.log(`  created ${orders.length} supply orders`);

  console.log('creating shipments...');
  const shipments = await createShipments({ orders, warehouse: ref.warehouse, batches: ref.batches });
  console.log(`  created ${shipments.length} shipments`);

  console.log('creating telemetry + excursions...');
  const excursions = await createTelemetryAndExcursions({ shipments });
  console.log(`  created excursions for ${excursions} shipment(s)`);

  console.log('creating complaints...');
  const complaints = await createComplaints({ shipments, ...ref });
  console.log(`  created ${complaints} complaints`);

  const counts = {
    demoOrders: await prisma.supplyOrder.count({ where: { id: { in: ALL_ORDER_IDS } } }),
    demoShipments: await prisma.shipment.count({ where: { id: { in: ALL_SHIPMENT_IDS } } }),
    demoTelemetry: await prisma.telemetryPoint.count({ where: { shipmentId: { in: ALL_SHIPMENT_IDS } } }),
    demoExcursions: await prisma.excursion.count({ where: { shipmentId: { in: ALL_SHIPMENT_IDS } } }),
    demoComplaints: await prisma.complaint.count({ where: { description: { startsWith: COMPLAINT_MARKER } } }),
    totalOrders: await prisma.supplyOrder.count(),
    totalShipments: await prisma.shipment.count(),
    // Proof the big reference dataset was never touched.
    ledgerRows: await prisma.stockLedger.count(),
    institutions: await prisma.institution.count(),
    drugs: await prisma.drug.count(),
    purchaseOrders: await prisma.purchaseOrder.count(),
  };
  console.log('demo overlay seeded:');
  for (const [k, v] of Object.entries(counts)) console.log(`  ${k.padEnd(16)} ${v}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
